import express from "express"; const router = express.Router();
import { registerUser, authUser, logoutUser, getUserProfile, updateUserProfile, getUsers, deleteUser, unlockUser } from "../controllers/userController";
import { protect, admin } from "../middleware/authMiddleware";
router.post("/", registerUser);
router.post("/login", authUser);
router.post("/logout", logoutUser);
router.route("/profile").get(protect, getUserProfile).put(protect, updateUserProfile);
router.route("/").get(protect, admin, getUsers);
router.route("/:id").delete(protect, admin, deleteUser);
router.route("/:id/unlock").put(protect, admin, unlockUser);
export default router;